import http from 'node:http';import {readFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';
import {Store,id} from './store.mjs';import {calculateRisk,evaluateProject,validateProject,validateScenario} from './methodology.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),store=new Store(path.resolve(process.env.DATA_DIR||path.join(root,'data')));await store.init();const port=Number(process.env.PORT||3000);
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json'};
async function body(req){let x='';for await(const c of req){x+=c;if(x.length>2e6)throw Object.assign(new Error('Request too large'),{status:413})}return x?JSON.parse(x):{}}
function send(res,status,x,type='application/json; charset=utf-8'){res.writeHead(status,{'content-type':type,'cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY'});res.end(type.startsWith('application/json')?JSON.stringify(x):x)}
function audit(p,action,actor='system',detail={}){p.audit.push({id:id(),at:new Date().toISOString(),action,actor,detail});p.updatedAt=new Date().toISOString()}
async function route(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);
 if(req.method==='GET'&&u.pathname==='/api/health')return send(res,200,{status:'ok',service:'CyberEvidence 21434',time:new Date().toISOString()});
 if(req.method==='GET'&&u.pathname==='/api/projects')return send(res,200,(await store.list()).map(p=>({id:p.id,name:p.name,item:p.item,owner:p.owner,updatedAt:p.updatedAt,assessment:evaluateProject(p)})));
 if(req.method==='POST'&&u.pathname==='/api/projects'){const x=await body(req),errors=validateProject(x);if(errors.length)return send(res,400,{errors});const p=await store.create({name:x.name.trim(),item:x.item.trim(),boundary:x.boundary.trim(),owner:x.owner.trim(),lifecycle:x.lifecycle||'Development',assets:Array.isArray(x.assets)?x.assets:[],scenarios:[],goals:[],evidence:[],reviews:[],audit:[]});audit(p,'PROJECT_CREATED',p.owner);await store.save(p);return send(res,201,{...p,assessment:evaluateProject(p)})}
 const m=u.pathname.match(/^\/api\/projects\/([a-f0-9-]+)(?:\/(scenarios|goals|evidence|reviews|report))?$/i);if(m&&req.method==='GET'&&!m[2]){const p=await store.get(m[1]);return send(res,200,{...p,assessment:evaluateProject(p)})}if(!m)return req.method==='GET'?staticFile(u,res):send(res,404,{error:'Not found'});
 const p=await store.get(m[1]);
 if(req.method==='GET'&&m[2]==='report')return send(res,200,{schemaVersion:'1.0',project:p,assessment:evaluateProject(p)});
 if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});const x=await body(req);
 if(m[2]==='scenarios'){const errors=validateScenario(x);if(errors.length)return send(res,400,{errors});const s={id:id(),title:x.title.trim(),asset:x.asset.trim(),damage:x.damage.trim(),threat:x.threat.trim(),attackPath:x.attackPath.trim(),impact:x.impact,feasibility:x.feasibility,risk:calculateRisk(x),treatment:x.treatment||'',owner:x.owner||'',status:x.status||'OPEN'};p.scenarios.push(s);audit(p,'SCENARIO_ADDED',x.actor||'user',{scenarioId:s.id,risk:s.risk.rating})}
 if(m[2]==='goals'){if(!x.title?.trim())return send(res,400,{error:'Goal title is required.'});const g={id:id(),title:x.title.trim(),requirement:x.requirement||'',scenarioIds:Array.isArray(x.scenarioIds)?x.scenarioIds:[],owner:x.owner||'',status:x.status||'DRAFT'};p.goals.push(g);audit(p,'GOAL_ADDED',x.actor||'user',{goalId:g.id})}
 if(m[2]==='evidence'){if(!x.title?.trim()||!x.type?.trim())return send(res,400,{error:'Evidence title and type are required.'});const e={id:id(),title:x.title.trim(),type:x.type.trim(),reference:x.reference||'',hash:x.hash||'',goalIds:Array.isArray(x.goalIds)?x.goalIds:[],validUntil:x.validUntil||'',owner:x.owner||'',status:x.status||'UNREVIEWED'};p.evidence.push(e);audit(p,'EVIDENCE_ADDED',x.actor||'user',{evidenceId:e.id})}
 if(m[2]==='reviews'){if(!x.reviewer?.trim()||!['APPROVED','REWORK','REJECTED'].includes(x.disposition))return send(res,400,{error:'Reviewer and valid disposition are required.'});const r={id:id(),reviewer:x.reviewer.trim(),scope:x.scope||'PROJECT',disposition:x.disposition,notes:x.notes||'',at:new Date().toISOString()};p.reviews.push(r);audit(p,'REVIEW_RECORDED',r.reviewer,{reviewId:r.id,disposition:r.disposition})}
 await store.save(p);return send(res,200,{...p,assessment:evaluateProject(p)});
}
async function staticFile(u,res){const f=u.pathname==='/'?'index.html':u.pathname.replace(/^\/+/,''),target=path.join(root,'public',path.normalize(f));if(!target.startsWith(path.join(root,'public')))return send(res,403,{error:'Forbidden'});try{return send(res,200,await readFile(target),mime[path.extname(target)]||'application/octet-stream')}catch{return send(res,404,{error:'Not found'})}}
http.createServer((req,res)=>route(req,res).catch(e=>{console.error(e);send(res,e.status||500,{error:e.message||'Unexpected error'})})).listen(port,'0.0.0.0',()=>console.log(`CyberEvidence listening on ${port}`));
